#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "/boot/home/config/settings/zsh/zprofile" ]]; then
  source "/boot/home/config/settings/zsh/zprofile"
fi

export ZDOTDIR="/boot/home/config/settings/zsh"
