#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "/boot/home/config/settings/zsh/zprezto/init.zsh" ]]; then
  source "/boot/home/config/settings/zsh/zprezto/init.zsh"
fi

# Customize to your needs...
